--create tables
CREATE TABLE folder (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder_name TEXT NOT NULL
);

--since folders exists, notes can have relationship to folder
CREATE TABLE note (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_name TEXT NOT NULL,
  note_content TEXT,
  modified TIMESTAMP DEFAULT now(),
  folder INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL
);
